name: doc
on:
  push:
    branches:
      - main       # main 分支 push 时触发
      - doc

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  doc:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install dependencies
        run: pnpm build

      - name: Build VitePress docs
        run: pnpm run build:doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

      - name: Deploy-pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
